feat(parser): add expect EOF in parseProgram to stop parsing if any invalid trailing tokens remain

diff --git a/compile b/compile
--- a/compile
+++ b/compile
@@ -1,9 +1,13 @@
 #!/bin/bash
+set -e # exit immediately if any command fails
 
 if [ "$1" = "--link" ]; then
     echo "Skipping compilation..."
 else
-    cabal run haskell-cc -- test.c
+    if ! cabal run haskell-cc -- test.c; then
+        echo "Compilation failed"
+        exit 1
+    fi
 fi
 
 as -o output.o output.asm
diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,2 +1,9 @@
-./compile
+#!/bin/bash
+
+set -e # exit immediately if any command fails
+
+if ! ./compile; then
+  exit 1
+fi
+
 ./program.out
